const data = [
  {
    id: 22,
    name: "Makita M18 100 Lumens LED Flashlight w/ 2.0ah Battery 1",
    slug: "makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1",
    permalink:
      "http://localhost:8888/wordpress/product/makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1/",
    date_created: "2022-11-12T00:59:15",
    date_created_gmt: "2022-11-12T00:59:15",
    date_modified: "2022-11-12T00:59:34",
    date_modified_gmt: "2022-11-12T00:59:34",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<p>Milwaukee M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0 ah Battery</p>\n<p>No Retail Box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>The MILWAUKEE M18 Work Light lasts 600X longer than conventional incandescent light bulbs. The LED work light is powered by M18 REDLITHIUM batteries, running up to 4X longer on a single charge. The work light features a 135 degree rotating head to easily direct the light beam at the desired work area and an integrated hook allows for hands-free use. The cordless work light features a sealed aluminum head to provide impact and weather resistance and comes with a limited lifetime LED warranty, the LEDs never need to be replaced.</p>\n<div class="grid bullet-list-wrapper">\n<ul class="bullet-list bullet-list--margin list list--type-square">\n<li class="list__item">100 Lumens of TRUEVIEW High Definition Output</li>\n<li class="list__item">TRUEVIEW High Definition Output provides neutral white color and produces an even beam pattern for clearer visibility</li>\n<li class="list__item">135 degree rotating head for flexible, focused illumination</li>\n<li class="list__item">Integrated hook for hands free use</li>\n<li class="list__item">Impact resistant lens</li>\n<li class="list__item">IP54 Rated: Water and Dust Resistant</li>\n<li class="list__item">5 Year Tool Warranty</li>\n<li class="list__item">LED Limited Lifetime Warranty: LEDs never need to be replaced</li>\n<li class="list__item">Includes: 2735-20 M18 Work Light</li>\n</ul>\n</div>\n',
    short_description:
      "<p>M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0ah Battery</p>\n<p>Model #2735-20<br />\nLasts 600X Longer than Conventional Incandescent Light Bulbs<br />\nTRUEVIEW High Definition Output Produces an Even Beam Pattern<br />\nIntegrated Hook Offers Hands Free Use</p>\n<p>Not in retail box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>Buy With Confidence!</p>\n<ul>\n<li>Free shipping on orders over $100.</li>\n<li>You can return new and unused items within 30 days.</li>\n</ul>\n",
    sku: "mwk-1-1-1-1",
    price: "50",
    regular_price: "56",
    sale_price: "50",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 10,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Milwaukee",
        slug: "milwaukee",
      },
    ],
    tags: [],
    images: [
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 13,
        date_created: "2022-11-12T00:53:53",
        date_created_gmt: "2022-11-12T00:53:53",
        date_modified: "2022-11-12T00:53:53",
        date_modified_gmt: "2022-11-12T00:53:53",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/6.jpeg",
        name: "6",
        alt: "",
      },
      {
        id: 14,
        date_created: "2022-11-12T00:53:54",
        date_created_gmt: "2022-11-12T00:53:54",
        date_modified: "2022-11-12T00:53:54",
        date_modified_gmt: "2022-11-12T00:53:54",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/20220515_115407-scaled.jpg",
        name: "20220515_115407",
        alt: "",
      },
      {
        id: 15,
        date_created: "2022-11-12T00:54:00",
        date_created_gmt: "2022-11-12T00:54:00",
        date_modified: "2022-11-12T00:54:00",
        date_modified_gmt: "2022-11-12T00:54:00",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/makitacircularsaw-scaled.jpg",
        name: "makitacircularsaw",
        alt: "",
      },
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 17,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/3.jpeg",
        name: "3",
        alt: "",
      },
      {
        id: 18,
        date_created: "2022-11-12T00:54:07",
        date_created_gmt: "2022-11-12T00:54:07",
        date_modified: "2022-11-12T00:54:07",
        date_modified_gmt: "2022-11-12T00:54:07",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/auction2.jpeg",
        name: "auction2",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>56.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span></ins>',
    related_ids: [12, 20, 21],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products",
        },
      ],
    },
  },

  {
    id: 22,
    name: "Makita M18 100 Lumens LED Flashlight w/ 2.0ah Battery 1",
    slug: "makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1",
    permalink:
      "http://localhost:8888/wordpress/product/makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1/",
    date_created: "2022-11-12T00:59:15",
    date_created_gmt: "2022-11-12T00:59:15",
    date_modified: "2022-11-12T00:59:34",
    date_modified_gmt: "2022-11-12T00:59:34",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<p>Milwaukee M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0 ah Battery</p>\n<p>No Retail Box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>The MILWAUKEE M18 Work Light lasts 600X longer than conventional incandescent light bulbs. The LED work light is powered by M18 REDLITHIUM batteries, running up to 4X longer on a single charge. The work light features a 135 degree rotating head to easily direct the light beam at the desired work area and an integrated hook allows for hands-free use. The cordless work light features a sealed aluminum head to provide impact and weather resistance and comes with a limited lifetime LED warranty, the LEDs never need to be replaced.</p>\n<div class="grid bullet-list-wrapper">\n<ul class="bullet-list bullet-list--margin list list--type-square">\n<li class="list__item">100 Lumens of TRUEVIEW High Definition Output</li>\n<li class="list__item">TRUEVIEW High Definition Output provides neutral white color and produces an even beam pattern for clearer visibility</li>\n<li class="list__item">135 degree rotating head for flexible, focused illumination</li>\n<li class="list__item">Integrated hook for hands free use</li>\n<li class="list__item">Impact resistant lens</li>\n<li class="list__item">IP54 Rated: Water and Dust Resistant</li>\n<li class="list__item">5 Year Tool Warranty</li>\n<li class="list__item">LED Limited Lifetime Warranty: LEDs never need to be replaced</li>\n<li class="list__item">Includes: 2735-20 M18 Work Light</li>\n</ul>\n</div>\n',
    short_description:
      "<p>M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0ah Battery</p>\n<p>Model #2735-20<br />\nLasts 600X Longer than Conventional Incandescent Light Bulbs<br />\nTRUEVIEW High Definition Output Produces an Even Beam Pattern<br />\nIntegrated Hook Offers Hands Free Use</p>\n<p>Not in retail box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>Buy With Confidence!</p>\n<ul>\n<li>Free shipping on orders over $100.</li>\n<li>You can return new and unused items within 30 days.</li>\n</ul>\n",
    sku: "mwk-1-1-1-1",
    price: "50",
    regular_price: "56",
    sale_price: "50",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 10,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Milwaukee",
        slug: "milwaukee",
      },
    ],
    tags: [],
    images: [
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 13,
        date_created: "2022-11-12T00:53:53",
        date_created_gmt: "2022-11-12T00:53:53",
        date_modified: "2022-11-12T00:53:53",
        date_modified_gmt: "2022-11-12T00:53:53",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/6.jpeg",
        name: "6",
        alt: "",
      },
      {
        id: 14,
        date_created: "2022-11-12T00:53:54",
        date_created_gmt: "2022-11-12T00:53:54",
        date_modified: "2022-11-12T00:53:54",
        date_modified_gmt: "2022-11-12T00:53:54",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/20220515_115407-scaled.jpg",
        name: "20220515_115407",
        alt: "",
      },
      {
        id: 15,
        date_created: "2022-11-12T00:54:00",
        date_created_gmt: "2022-11-12T00:54:00",
        date_modified: "2022-11-12T00:54:00",
        date_modified_gmt: "2022-11-12T00:54:00",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/makitacircularsaw-scaled.jpg",
        name: "makitacircularsaw",
        alt: "",
      },
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 17,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/3.jpeg",
        name: "3",
        alt: "",
      },
      {
        id: 18,
        date_created: "2022-11-12T00:54:07",
        date_created_gmt: "2022-11-12T00:54:07",
        date_modified: "2022-11-12T00:54:07",
        date_modified_gmt: "2022-11-12T00:54:07",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/auction2.jpeg",
        name: "auction2",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>56.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span></ins>',
    related_ids: [12, 20, 21],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 22,
    name: "Makita M18 100 Lumens LED Flashlight w/ 2.0ah Battery 1",
    slug: "makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1",
    permalink:
      "http://localhost:8888/wordpress/product/makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1/",
    date_created: "2022-11-12T00:59:15",
    date_created_gmt: "2022-11-12T00:59:15",
    date_modified: "2022-11-12T00:59:34",
    date_modified_gmt: "2022-11-12T00:59:34",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<p>Milwaukee M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0 ah Battery</p>\n<p>No Retail Box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>The MILWAUKEE M18 Work Light lasts 600X longer than conventional incandescent light bulbs. The LED work light is powered by M18 REDLITHIUM batteries, running up to 4X longer on a single charge. The work light features a 135 degree rotating head to easily direct the light beam at the desired work area and an integrated hook allows for hands-free use. The cordless work light features a sealed aluminum head to provide impact and weather resistance and comes with a limited lifetime LED warranty, the LEDs never need to be replaced.</p>\n<div class="grid bullet-list-wrapper">\n<ul class="bullet-list bullet-list--margin list list--type-square">\n<li class="list__item">100 Lumens of TRUEVIEW High Definition Output</li>\n<li class="list__item">TRUEVIEW High Definition Output provides neutral white color and produces an even beam pattern for clearer visibility</li>\n<li class="list__item">135 degree rotating head for flexible, focused illumination</li>\n<li class="list__item">Integrated hook for hands free use</li>\n<li class="list__item">Impact resistant lens</li>\n<li class="list__item">IP54 Rated: Water and Dust Resistant</li>\n<li class="list__item">5 Year Tool Warranty</li>\n<li class="list__item">LED Limited Lifetime Warranty: LEDs never need to be replaced</li>\n<li class="list__item">Includes: 2735-20 M18 Work Light</li>\n</ul>\n</div>\n',
    short_description:
      "<p>M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0ah Battery</p>\n<p>Model #2735-20<br />\nLasts 600X Longer than Conventional Incandescent Light Bulbs<br />\nTRUEVIEW High Definition Output Produces an Even Beam Pattern<br />\nIntegrated Hook Offers Hands Free Use</p>\n<p>Not in retail box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>Buy With Confidence!</p>\n<ul>\n<li>Free shipping on orders over $100.</li>\n<li>You can return new and unused items within 30 days.</li>\n</ul>\n",
    sku: "mwk-1-1-1-1",
    price: "50",
    regular_price: "56",
    sale_price: "50",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 10,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Milwaukee",
        slug: "milwaukee",
      },
    ],
    tags: [],
    images: [
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 13,
        date_created: "2022-11-12T00:53:53",
        date_created_gmt: "2022-11-12T00:53:53",
        date_modified: "2022-11-12T00:53:53",
        date_modified_gmt: "2022-11-12T00:53:53",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/6.jpeg",
        name: "6",
        alt: "",
      },
      {
        id: 14,
        date_created: "2022-11-12T00:53:54",
        date_created_gmt: "2022-11-12T00:53:54",
        date_modified: "2022-11-12T00:53:54",
        date_modified_gmt: "2022-11-12T00:53:54",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/20220515_115407-scaled.jpg",
        name: "20220515_115407",
        alt: "",
      },
      {
        id: 15,
        date_created: "2022-11-12T00:54:00",
        date_created_gmt: "2022-11-12T00:54:00",
        date_modified: "2022-11-12T00:54:00",
        date_modified_gmt: "2022-11-12T00:54:00",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/makitacircularsaw-scaled.jpg",
        name: "makitacircularsaw",
        alt: "",
      },
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 17,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/3.jpeg",
        name: "3",
        alt: "",
      },
      {
        id: 18,
        date_created: "2022-11-12T00:54:07",
        date_created_gmt: "2022-11-12T00:54:07",
        date_modified: "2022-11-12T00:54:07",
        date_modified_gmt: "2022-11-12T00:54:07",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/auction2.jpeg",
        name: "auction2",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>56.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span></ins>',
    related_ids: [12, 20, 21],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 22,
    name: "Makita M18 100 Lumens LED Flashlight w/ 2.0ah Battery 1",
    slug: "makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1",
    permalink:
      "http://localhost:8888/wordpress/product/makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1/",
    date_created: "2022-11-12T00:59:15",
    date_created_gmt: "2022-11-12T00:59:15",
    date_modified: "2022-11-12T00:59:34",
    date_modified_gmt: "2022-11-12T00:59:34",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<p>Milwaukee M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0 ah Battery</p>\n<p>No Retail Box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>The MILWAUKEE M18 Work Light lasts 600X longer than conventional incandescent light bulbs. The LED work light is powered by M18 REDLITHIUM batteries, running up to 4X longer on a single charge. The work light features a 135 degree rotating head to easily direct the light beam at the desired work area and an integrated hook allows for hands-free use. The cordless work light features a sealed aluminum head to provide impact and weather resistance and comes with a limited lifetime LED warranty, the LEDs never need to be replaced.</p>\n<div class="grid bullet-list-wrapper">\n<ul class="bullet-list bullet-list--margin list list--type-square">\n<li class="list__item">100 Lumens of TRUEVIEW High Definition Output</li>\n<li class="list__item">TRUEVIEW High Definition Output provides neutral white color and produces an even beam pattern for clearer visibility</li>\n<li class="list__item">135 degree rotating head for flexible, focused illumination</li>\n<li class="list__item">Integrated hook for hands free use</li>\n<li class="list__item">Impact resistant lens</li>\n<li class="list__item">IP54 Rated: Water and Dust Resistant</li>\n<li class="list__item">5 Year Tool Warranty</li>\n<li class="list__item">LED Limited Lifetime Warranty: LEDs never need to be replaced</li>\n<li class="list__item">Includes: 2735-20 M18 Work Light</li>\n</ul>\n</div>\n',
    short_description:
      "<p>M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0ah Battery</p>\n<p>Model #2735-20<br />\nLasts 600X Longer than Conventional Incandescent Light Bulbs<br />\nTRUEVIEW High Definition Output Produces an Even Beam Pattern<br />\nIntegrated Hook Offers Hands Free Use</p>\n<p>Not in retail box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>Buy With Confidence!</p>\n<ul>\n<li>Free shipping on orders over $100.</li>\n<li>You can return new and unused items within 30 days.</li>\n</ul>\n",
    sku: "mwk-1-1-1-1",
    price: "50",
    regular_price: "56",
    sale_price: "50",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 10,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Milwaukee",
        slug: "milwaukee",
      },
    ],
    tags: [],
    images: [
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 13,
        date_created: "2022-11-12T00:53:53",
        date_created_gmt: "2022-11-12T00:53:53",
        date_modified: "2022-11-12T00:53:53",
        date_modified_gmt: "2022-11-12T00:53:53",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/6.jpeg",
        name: "6",
        alt: "",
      },
      {
        id: 14,
        date_created: "2022-11-12T00:53:54",
        date_created_gmt: "2022-11-12T00:53:54",
        date_modified: "2022-11-12T00:53:54",
        date_modified_gmt: "2022-11-12T00:53:54",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/20220515_115407-scaled.jpg",
        name: "20220515_115407",
        alt: "",
      },
      {
        id: 15,
        date_created: "2022-11-12T00:54:00",
        date_created_gmt: "2022-11-12T00:54:00",
        date_modified: "2022-11-12T00:54:00",
        date_modified_gmt: "2022-11-12T00:54:00",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/makitacircularsaw-scaled.jpg",
        name: "makitacircularsaw",
        alt: "",
      },
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 17,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/3.jpeg",
        name: "3",
        alt: "",
      },
      {
        id: 18,
        date_created: "2022-11-12T00:54:07",
        date_created_gmt: "2022-11-12T00:54:07",
        date_modified: "2022-11-12T00:54:07",
        date_modified_gmt: "2022-11-12T00:54:07",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/auction2.jpeg",
        name: "auction2",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>56.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span></ins>',
    related_ids: [12, 20, 21],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 22,
    name: "Makita M18 100 Lumens LED Flashlight w/ 2.0ah Battery 1",
    slug: "makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1",
    permalink:
      "http://localhost:8888/wordpress/product/makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1/",
    date_created: "2022-11-12T00:59:15",
    date_created_gmt: "2022-11-12T00:59:15",
    date_modified: "2022-11-12T00:59:34",
    date_modified_gmt: "2022-11-12T00:59:34",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<p>Milwaukee M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0 ah Battery</p>\n<p>No Retail Box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>The MILWAUKEE M18 Work Light lasts 600X longer than conventional incandescent light bulbs. The LED work light is powered by M18 REDLITHIUM batteries, running up to 4X longer on a single charge. The work light features a 135 degree rotating head to easily direct the light beam at the desired work area and an integrated hook allows for hands-free use. The cordless work light features a sealed aluminum head to provide impact and weather resistance and comes with a limited lifetime LED warranty, the LEDs never need to be replaced.</p>\n<div class="grid bullet-list-wrapper">\n<ul class="bullet-list bullet-list--margin list list--type-square">\n<li class="list__item">100 Lumens of TRUEVIEW High Definition Output</li>\n<li class="list__item">TRUEVIEW High Definition Output provides neutral white color and produces an even beam pattern for clearer visibility</li>\n<li class="list__item">135 degree rotating head for flexible, focused illumination</li>\n<li class="list__item">Integrated hook for hands free use</li>\n<li class="list__item">Impact resistant lens</li>\n<li class="list__item">IP54 Rated: Water and Dust Resistant</li>\n<li class="list__item">5 Year Tool Warranty</li>\n<li class="list__item">LED Limited Lifetime Warranty: LEDs never need to be replaced</li>\n<li class="list__item">Includes: 2735-20 M18 Work Light</li>\n</ul>\n</div>\n',
    short_description:
      "<p>M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0ah Battery</p>\n<p>Model #2735-20<br />\nLasts 600X Longer than Conventional Incandescent Light Bulbs<br />\nTRUEVIEW High Definition Output Produces an Even Beam Pattern<br />\nIntegrated Hook Offers Hands Free Use</p>\n<p>Not in retail box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>Buy With Confidence!</p>\n<ul>\n<li>Free shipping on orders over $100.</li>\n<li>You can return new and unused items within 30 days.</li>\n</ul>\n",
    sku: "mwk-1-1-1-1",
    price: "50",
    regular_price: "56",
    sale_price: "50",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 10,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Milwaukee",
        slug: "milwaukee",
      },
    ],
    tags: [],
    images: [
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 13,
        date_created: "2022-11-12T00:53:53",
        date_created_gmt: "2022-11-12T00:53:53",
        date_modified: "2022-11-12T00:53:53",
        date_modified_gmt: "2022-11-12T00:53:53",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/6.jpeg",
        name: "6",
        alt: "",
      },
      {
        id: 14,
        date_created: "2022-11-12T00:53:54",
        date_created_gmt: "2022-11-12T00:53:54",
        date_modified: "2022-11-12T00:53:54",
        date_modified_gmt: "2022-11-12T00:53:54",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/20220515_115407-scaled.jpg",
        name: "20220515_115407",
        alt: "",
      },
      {
        id: 15,
        date_created: "2022-11-12T00:54:00",
        date_created_gmt: "2022-11-12T00:54:00",
        date_modified: "2022-11-12T00:54:00",
        date_modified_gmt: "2022-11-12T00:54:00",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/makitacircularsaw-scaled.jpg",
        name: "makitacircularsaw",
        alt: "",
      },
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 17,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/3.jpeg",
        name: "3",
        alt: "",
      },
      {
        id: 18,
        date_created: "2022-11-12T00:54:07",
        date_created_gmt: "2022-11-12T00:54:07",
        date_modified: "2022-11-12T00:54:07",
        date_modified_gmt: "2022-11-12T00:54:07",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/auction2.jpeg",
        name: "auction2",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>56.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span></ins>',
    related_ids: [12, 20, 21],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 22,
    name: "Makita M18 100 Lumens LED Flashlight w/ 2.0ah Battery 1",
    slug: "makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1",
    permalink:
      "http://localhost:8888/wordpress/product/makita-m18-100-lumens-led-flashlight-w-2-0ah-battery-1/",
    date_created: "2022-11-12T00:59:15",
    date_created_gmt: "2022-11-12T00:59:15",
    date_modified: "2022-11-12T00:59:34",
    date_modified_gmt: "2022-11-12T00:59:34",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<p>Milwaukee M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0 ah Battery</p>\n<p>No Retail Box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>The MILWAUKEE M18 Work Light lasts 600X longer than conventional incandescent light bulbs. The LED work light is powered by M18 REDLITHIUM batteries, running up to 4X longer on a single charge. The work light features a 135 degree rotating head to easily direct the light beam at the desired work area and an integrated hook allows for hands-free use. The cordless work light features a sealed aluminum head to provide impact and weather resistance and comes with a limited lifetime LED warranty, the LEDs never need to be replaced.</p>\n<div class="grid bullet-list-wrapper">\n<ul class="bullet-list bullet-list--margin list list--type-square">\n<li class="list__item">100 Lumens of TRUEVIEW High Definition Output</li>\n<li class="list__item">TRUEVIEW High Definition Output provides neutral white color and produces an even beam pattern for clearer visibility</li>\n<li class="list__item">135 degree rotating head for flexible, focused illumination</li>\n<li class="list__item">Integrated hook for hands free use</li>\n<li class="list__item">Impact resistant lens</li>\n<li class="list__item">IP54 Rated: Water and Dust Resistant</li>\n<li class="list__item">5 Year Tool Warranty</li>\n<li class="list__item">LED Limited Lifetime Warranty: LEDs never need to be replaced</li>\n<li class="list__item">Includes: 2735-20 M18 Work Light</li>\n</ul>\n</div>\n',
    short_description:
      "<p>M18 18-Volt Lithium-Ion Cordless 100 Lumens LED Flashlight w/ 2.0ah Battery</p>\n<p>Model #2735-20<br />\nLasts 600X Longer than Conventional Incandescent Light Bulbs<br />\nTRUEVIEW High Definition Output Produces an Even Beam Pattern<br />\nIntegrated Hook Offers Hands Free Use</p>\n<p>Not in retail box. These items were pulled out from large multi tool combo kit packages. All products are brand new and come with manual.</p>\n<p>Buy With Confidence!</p>\n<ul>\n<li>Free shipping on orders over $100.</li>\n<li>You can return new and unused items within 30 days.</li>\n</ul>\n",
    sku: "mwk-1-1-1-1",
    price: "50",
    regular_price: "56",
    sale_price: "50",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 10,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Milwaukee",
        slug: "milwaukee",
      },
    ],
    tags: [],
    images: [
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 13,
        date_created: "2022-11-12T00:53:53",
        date_created_gmt: "2022-11-12T00:53:53",
        date_modified: "2022-11-12T00:53:53",
        date_modified_gmt: "2022-11-12T00:53:53",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/6.jpeg",
        name: "6",
        alt: "",
      },
      {
        id: 14,
        date_created: "2022-11-12T00:53:54",
        date_created_gmt: "2022-11-12T00:53:54",
        date_modified: "2022-11-12T00:53:54",
        date_modified_gmt: "2022-11-12T00:53:54",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/20220515_115407-scaled.jpg",
        name: "20220515_115407",
        alt: "",
      },
      {
        id: 15,
        date_created: "2022-11-12T00:54:00",
        date_created_gmt: "2022-11-12T00:54:00",
        date_modified: "2022-11-12T00:54:00",
        date_modified_gmt: "2022-11-12T00:54:00",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/makitacircularsaw-scaled.jpg",
        name: "makitacircularsaw",
        alt: "",
      },
      {
        id: 16,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/4.jpeg",
        name: "4",
        alt: "",
      },
      {
        id: 17,
        date_created: "2022-11-12T00:54:06",
        date_created_gmt: "2022-11-12T00:54:06",
        date_modified: "2022-11-12T00:54:06",
        date_modified_gmt: "2022-11-12T00:54:06",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/3.jpeg",
        name: "3",
        alt: "",
      },
      {
        id: 18,
        date_created: "2022-11-12T00:54:07",
        date_created_gmt: "2022-11-12T00:54:07",
        date_modified: "2022-11-12T00:54:07",
        date_modified_gmt: "2022-11-12T00:54:07",
        src: "http://localhost:8888/wordpress/wp-content/uploads/2022/11/auction2.jpeg",
        name: "auction2",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>56.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>50.00</bdi></span></ins>',
    related_ids: [12, 20, 21],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://localhost:8888/wordpress/wp-json/wc/v3/products",
        },
      ],
    },
  },
];

export default data;
